-- ============================================================
-- upgrade_v5.sql
--
-- Run this if you already had the previous version installed and want
-- the new Great Himalayan Trail map + clickable mountain profile posts
-- without re-importing everything from scratch.
--
-- No schema changes here -- just new rows in the existing `posts` table.
-- The image files must also exist under assets/images/.
--
-- Docker command:
-- docker compose exec -T db mysql -u root -proot_password_change_me
-- seatosummit < upgrade_v5.sql
-- ============================================================

USE seatosummit;

INSERT IGNORE INTO posts (slug, title, excerpt, body, image_url, is_published, published_at) VALUES
('chyoro-ri', 'Chyoro Ri (6,034m)', 'A remote trekking peak in far-western Nepal, marking the wild western end of the Great Himalayan Trail.', 'Chyoro Ri stands at 6,034 metres in the remote far-west of Nepal, close to Rara Lake and the Shey Phoksundo region -- some of the least-visited high country in the entire Himalaya. Along the Great Himalayan Trail, this section marks the wild western frontier of the route, days from the nearest road, where trails pass through Rara National Park and skirt the edge of Dolpo.\n\nFew trekkers make it this far west, which is exactly the appeal: empty trails, untouched Tibetan-influenced villages, and mountain wilderness that seems to stretch forever. Our western GHT departures include this stretch for trekkers who want to see Nepal well beyond the popular circuits.', 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=900', 1, CURDATE()),
('dhaulagiri', 'Dhaulagiri (8,167m)', 'The world''s seventh-highest mountain, and one of the most dramatic massifs on the Great Himalayan Trail.', 'At 8,167 metres, Dhaulagiri is the seventh-highest mountain on Earth and the dominant peak of its own range, rising dramatically above the Kali Gandaki -- the deepest gorge in the world. Its name means "White Mountain" in Sanskrit, and on a clear day its enormous south face is visible from as far away as Pokhara.\n\nOn the Great Himalayan Trail, the Dhaulagiri massif marks the transition out of the Annapurna region into the trail''s central stretch. The classic Dhaulagiri Circuit, crossing French Col and Dhampus Pass above 5,000 metres, is one of the most demanding and rewarding high routes in Nepal, and forms part of several of our custom western-trail itineraries.', 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=900', 1, CURDATE()),
('annapurna', 'Annapurna (8,091m)', 'The tenth-highest mountain in the world and the centrepiece of one of Nepal''s most iconic trekking regions.', 'Annapurna I rises to 8,091 metres and gives its name to the entire massif and conservation area that surrounds it -- home to the classic Annapurna Circuit and Annapurna Base Camp treks. The name means "Goddess of the Harvests" in Sanskrit, reflecting its significance to the farming communities in its shadow.\n\nOn the Great Himalayan Trail, the Annapurna section is one of the most visually spectacular, with the trail weaving beneath the massif''s southern flank before continuing east toward Manaslu. Our <a href="trek-detail.php?slug=annapurna-circuit">Annapurna Circuit trek</a> covers much of this same ground for trekkers who want the highlights without the full end-to-end GHT commitment.', 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=900', 1, CURDATE()),
('ganesh-himal', 'Ganesh Himal (7,422m)', 'A lesser-visited range named for Ganesh, the elephant-headed Hindu deity, between Manaslu and Langtang.', 'Ganesh Himal reaches 7,422 metres and sits in a quiet stretch of the Himalaya between the more famous Manaslu and Langtang ranges. It''s named for Ganesh, the elephant-headed Hindu god of new beginnings, and the massif has a similarly rounded, distinctive silhouette when viewed from the trail.\n\nBecause it lies off the main circuit routes, the Ganesh Himal section of the Great Himalayan Trail sees far fewer trekkers than its neighbours, offering a genuine sense of wilderness and untouched Tamang and Gurung villages along the connecting trails between Manaslu and Langtang.', 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=900', 1, CURDATE()),
('manaslu', 'Manaslu (8,163m)', 'The eighth-highest mountain in the world, known as the ''Mountain of the Spirit.''', 'Manaslu stands 8,163 metres tall and takes its name from the Sanskrit word for "soul" or "spirit" -- fitting for a mountain long regarded as sacred by the communities who live in its valleys. It was first summited in 1956 by a Japanese expedition, and the Manaslu region remains one of the more remote and restricted parts of Nepal open to trekkers.\n\nThe Manaslu Circuit, crossing the dramatic Larkya La Pass at 5,106 metres, is widely considered one of the finest alternatives to the busier Everest and Annapurna routes, and forms a key link in the middle section of the Great Himalayan Trail. See our full <a href="trek-detail.php?slug=manaslu-circuit">Manaslu Circuit itinerary</a> for the standalone version of this route.', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=900', 1, CURDATE()),
('langtang', 'Langtang Lirung (7,234m)', 'The closest major Himalayan peak to Kathmandu, and heart of the ''valley of glaciers.''', 'Langtang Lirung rises to 7,234 metres above the Langtang Valley, often called the "valley of glaciers" and the closest major Himalayan range to Kathmandu -- reachable by road in under a day. The valley was badly affected by the 2015 earthquake, which triggered a landslide that devastated Langtang village; the community has since rebuilt, and the trail welcomes trekkers again.\n\nOn the Great Himalayan Trail, Langtang connects the Ganesh Himal section to the high passes of Panch Pokhari and on toward the Everest region, and the standalone <a href="trek-detail.php?slug=langtang-valley">Langtang Valley Trek</a> remains one of our best-value itineraries for trekkers short on time.', 'https://images.unsplash.com/photo-1516481352817-1e5efaa39e6a?w=900', 1, CURDATE()),
('mount-everest', 'Mount Everest / Sagarmatha (8,848m)', 'The highest point on Earth, and the mountain most Nepal treks are named for.', 'At 8,848 metres, Everest -- known in Nepal as Sagarmatha, "Forehead of the Sky" -- is the highest point on the planet and the mountain that first put Himalayan trekking on the map worldwide. It sits within Sagarmatha National Park, a UNESCO World Heritage Site, surrounded by other giants including Lhotse, Nuptse, and Ama Dablam.\n\nMost trekkers experience Everest not by climbing it but by trekking to Everest Base Camp or the sunrise viewpoint of Kala Patthar, both covered in detail on our <a href="trek-detail.php?slug=everest-base-camp">Everest Base Camp trek</a>. On the Great Himalayan Trail, the Everest region marks roughly the halfway point of the full east-west route.', 'https://images.unsplash.com/photo-1544198365-f5d60b6d8190?w=900', 1, CURDATE()),
('gokyo-ri', 'Gokyo Ri (5,357m)', 'A trekking peak above the turquoise Gokyo Lakes, with one of the best panoramic views in the Khumbu.', 'Gokyo Ri is a 5,357-metre viewpoint above the string of turquoise Gokyo Lakes on the western side of the Khumbu valley, a short but steep climb rewarded with one of the widest panoramas in the entire Everest region -- four peaks above 8,000 metres visible at once, including Everest, Lhotse, Makalu, and Cho Oyu.\n\nMany trekkers combine a visit to Gokyo Ri with the classic Everest Base Camp route via the Cho La Pass, making it a highlight for those with a little extra time in the Khumbu.', 'https://images.unsplash.com/photo-1516481352817-1e5efaa39e6a?w=900', 1, CURDATE()),
('lhotse', 'Lhotse (8,516m)', 'The fourth-highest mountain in the world, directly connected to Everest by the South Col.', 'Lhotse reaches 8,516 metres, making it the fourth-highest mountain on Earth, and is physically connected to Everest via the South Col -- the two share much of the same climbing route up to that point. Its name means "South Peak" in Tibetan, reflecting its position just south of Everest''s summit.\n\nWhile Lhotse itself is a serious mountaineering objective rather than a trekking destination, it dominates the skyline throughout the Everest Base Camp trek and is one of the most photographed peaks from Kala Patthar and Gokyo Ri.', 'https://images.unsplash.com/photo-1544198365-f5d60b6d8190?w=900', 1, CURDATE()),
('makalu', 'Makalu (8,485m)', 'The fifth-highest mountain in the world, a striking four-sided pyramid east of Everest.', 'Makalu stands 8,485 metres tall, the fifth-highest mountain in the world, and is instantly recognisable by its steep, four-sided pyramid shape rising isolated from the surrounding ridgelines east of Everest. Unlike its famous neighbour, Makalu sees relatively few visitors -- the approach trek is longer, wilder, and considerably less developed.\n\nOn the Great Himalayan Trail, the Makalu section is among the most physically demanding, crossing high, remote passes with minimal infrastructure -- a highlight for experienced trekkers looking for genuine solitude between the Everest and Kangchenjunga regions.', 'https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=900', 1, CURDATE()),
('kangchenjunga', 'Kangchenjunga (8,586m)', 'The third-highest mountain in the world, straddling the Nepal-India border and considered sacred.', 'Kangchenjunga rises to 8,586 metres on the Nepal-India border, the third-highest mountain in the world and the easternmost giant on the Great Himalayan Trail. Its name means "Five Treasures of the Snow," referring to its five distinct summits, and it holds deep spiritual significance for the local Sikkimese and Nepali communities -- by tradition, some early expeditions stopped just short of the true summit out of respect for that belief.\n\nThe Kangchenjunga region marks the eastern terminus of the full Great Himalayan Trail, a remote and rarely-trekked corner of Nepal bordering Sikkim, rich in biodiversity and largely untouched by mass tourism.', 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=900', 1, CURDATE());
